server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/db_students
    username: magadiflo
    password: magadiflo

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.hibernate.SQL: debug

management:
  tracing:
    sampling:
      probability: 1.0